trigger: none

pool:
 name: TestPool
 demands:
 - Agent.OS -equals Linux

steps:
    inputs:
      provider: 'azurerm'
      command: 'init'
     
    inputs:
      provider: 'azurerm'
      command: 'apply'