trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
   terraformVersion: $(terraformVersion)

- script: |
      terraform init
      terraform apply -auto-approve
  displayName: "Terraform Apply"