# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
steps:

- task: TerraformInstaller
  displayName: install terraform
  inputs:
  terraformVersion: latest 
  appendCommitMessageToRunName:


- task: TerraformCLI
  displayName: 'terraform init'
  inputs:
    command: init
    environmentServiceName: 'My Azure Service Connection'
    # indicate az login should be run as part of this command
    runAzLogin: true

- task: TerraformCLI
  displayName: 'terraform apply'
  inputs:
    command: apply
    environmentServiceName: 'My Azure Service Connection'
    # indicate az login should be run as part of this command
    runAzLogin: true